#ifndef _FFMPEG_CORE_VERSION
#define _FFMPEG_CORE_VERSION
#define FFMPEG_CORE_VERSION_MAJOR 1
#define FFMPEG_CORE_VERSION_MINOR 0
#define FFMPEG_CORE_VERSION_MICRO 0
#define FFMPEG_CORE_VERSION_REV 0
#define FFMPEG_CORE_VERSION "1.0.0.0"
#define FFMPEG_CORE_VERSION_INT (((int32_t)FFMPEG_CORE_VERSION_MAJOR << 24) | ((int32_t)FFMPEG_CORE_VERSION_MINOR << 16) | ((int32_t)FFMPEG_CORE_VERSION_MICRO << 8) | (int32_t)FFMPEG_CORE_VERSION_REV)
#endif
